services:
  protonmail-bridge:
    image: dancwilliams/protonmail-bridge:latest@sha256:004c1b035bb9bb92ad4d5b1227b578be12a3722086d160854d02242d5dc76fa2
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  protonmail:
    name: protonmail
