version: '2.1'

services:
  protonmail-bridge:
    image: ghcr.io/trent-maetzold/protonmail-bridge:build
    ports:
      - 127.0.0.1:1025:25/tcp
      - 127.0.0.1:1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
