name: update check

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/update-check.yaml
      - update-check.py
  pull_request:
    paths:
      - .github/workflows/update-check.yaml
      - update-check.py
  schedule:
  - cron: '0 0 * * *'  # runs everyday at midnight

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Check Update
      run: python3 update-check.py ${{ github.event_name == 'pull_request' }}
