name: update check

on:
  push:
    paths:
      - .github/workflows/update-check.yaml
      - update-check.py
  pull_request:
    paths:
      - .github/workflows/update-check.yaml
      - update-check.py
  schedule:
  - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Install dependencies
      run: pip install requests
    - name: Check Update
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python3 update-check.py ${{ github.event_name == 'pull_request' }}
